spring:
  application:
    name: CognitiveQuery

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user, user:email
            redirect-uri: http://localhost:8080/login/oauth2/code/github

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true

github:
  token:
    url: https://github.com/login/oauth/access_token
  user:
    info:
      url: https://api.github.com/user

app:
  oauth:
    state:
      ttl:
        minutes: 10
  analysis:
    output:
      base-path: ${BASE_PATH}

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}

backend:
  api:
    base-url: ${BACKEND_BASE_URL}

google:
  gemini:
    api:
      key: ${GEMINI_API_KEY}
      model: gemini-1.5-flash
      base-url: https://generativelanguage.googleapis.com/v1beta